# Generated by Django 5.1 on 2024-08-10 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mommymomeatsapp', '0003_rename_attraction_reason_ingredient_attract_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='attract_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='PotentialRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregnancy_week_start', models.IntegerField()),
                ('pregnancy_week_end', models.IntegerField()),
                ('risk_level', models.CharField(max_length=50)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mommymomeatsapp.ingredient')),
            ],
        ),
    ]
