# Generated by Django 5.1 on 2024-08-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mommymomeatsapp', '0004_alter_ingredient_attract_reason_potentialrisk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='kcal',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
